#:schema node_modules/wrangler/config-schema.json
name = "wednesday"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MASTODON_TOKEN = ""
# MASTODON_WEDNESDAY_DUDE_MEDIA = ""
