#:schema node_modules/wrangler/config-schema.json
name = "wednesday"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [ "0 8 * * wed" ]

[[r2_buckets]]
binding = 'RESOURCES'
bucket_name = 'resources'
