name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Create deployment package
        run: zip -r deployment-package.zip .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Update Lambda environment variables
        run: aws lambda update-function-configuration --function-name wednesday --environment Variables="{MASTODON_ACCESS_KEY=${{ secrets.MASTODON_ACCESS_KEY }}}"
      
      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name wednesday --zip-file fileb://deployment-package.zip
